#! /bin/sh
# Copyright (C) 2005 Marco Sinhoreli
# Leonardo Rodrigues de Mello 2006
# edited on: Ter Out 10 14:57:55 BRT 2006
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# 29/06/2005



for i in $(xm list | grep xen | awk '{print $1}')
  do
  HRS=( $(cat /etc/passwd | grep ",$i," | cut -d "|" -f 6,7  | sed 's/|/ /g') )
  if [ ${HRS[0]} -ne 0 ] || [ ${HRS[1]} -ne 0 ];
      then
      if [ $(date +%H) -gt ${HRS[1]} ] || [ $(date +%H) -lt ${HRS[0]} ];
	  then
	  xm shutdown $i
	  echo "xenprogd - $i - $(date) - shutdown" >> /var/log/xenprogd.log
      fi
  fi
done
