#!/bin/bash
echo "Criando Usuário Demo para o sistema"
echo "Lembre-se de digitar uma senha para o usuário demo na hora que for solicitado"
groupadd xen 
adduser --gecos "Xenprog demo,TEST,@,xen204,||06-07-06|06-12-09|1-2-3-4-5-6-7|00|00|0"  --shell /bin/xensh  --ingroup xen demo
