#! /bin/sh

# Copyright (C) 2005 Marco Sinhoreli
# Leonardo Rodrigues de Mello 2006
# edited on: Qua,  5 de Jul de 2006
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# 29/06/2005

# Importacao das variaveis de sistema
if [ -f ./vars.config ]
then 
	. ./vars.config
else
	if [ -f /etc/xensh/vars.config ]
	then 
	   . /etc/xensh/vars.config
	else
	   echo "Arquivo de configuracao nao existe"
	   echo "Abortando Programa"
	   exit 1
	fi
fi

echo $SESSION
echo $INSTITUTION
echo $NOME_CURSO
echo $EMAIL_CURSO
echo $IP_SERVIDOR
echo $PORTA_SERVIDOR
echo $XEN_CONF
echo $XEN_VBD

sleep 2
#  Menu principal da Ferramenta

menu(){
    
    OPT=$(DIALOG \
	--help-button \
	--ok-label "Selecionar" \
	--cancel-label "Sair" \
	--menu "Escolha uma opcao:" 0 0 0 \
	1 "Gerenciamento de usuarios e Maquinas Virtuais" \
	2 "Adicionar Usuario/Maquina Virtual" \
	3 "Reinstalar Maquina Virtual com problemas" \
	4 "Remover Maquina Virtual e usuario" \
	5 "Ver status do sistema" )
    
    case $? in
	1|255) exit 0 ;;
	2) 
	    case $OPT in
		"HELP 1")
		    DIALOG --ok-label "Menu" --backtitle "Gerenciamento de usuários e Maquinas Virtuais" --msgbox "
Visualize e altere as configuracoes dos usuarios como:
  - Nome
  - e-mail
  - Turma
  - Intervalo/Horas/dias da semana de uso de Maquinas Virtuais
  - Status do perfil
  - Log de acesso
" 20 70;;
		"HELP 2")
		    DIALOG \
			--ok-label "Menu" \
			--backtitle "Adicionar Usuario/Maquina Virtual" \
			--msgbox "
Adiciona um novo usuario e uma nova Maquina Virtual.
" 20 70;;
		
		"HELP 3")
		    DIALOG \
			--ok-label "Menu" \
			--backtitle "Reinstalar Maquina Virtual com problemas" \
			--msgbox "
Reinstala Maquina Virtual em mau funcionamento por motivos
de uso.
" 20 70;;
		
		"HELP 4")
		    DIALOG \
			--ok-label "Menu" \
			--backtitle "Remover Maquina Virtual e usuario" \
			--msgbox "
Remove Maquina Virtual e usuario a ela relacionado.
" 20 70;;
		
		"HELP 5")
		    DIALOG \
			--ok-label "Menu" \
			--backtitle "Ver status do sistema" \
			--msgbox "
Visualiza todos os dados relativos ao sistema de Maquinas Virtuais:
  - Total de Maquinas Virtuais on-line
  - Capacidade do Linux Volume Manager
  - Recursos disponiveis de hardware
  - log do sistema
" 20 70;;
	    esac
	    menu ;;
    esac
    
    case $OPT in
	1) 
	    gerenciamento
	    ;;
	2) 
	    create_xen
	    ;;
	3) 
	    list_concerta
	    ;;
	4) 
	    list_remove
	    ;;
	5) 
	    status_menu
	    ;;
    esac
}

# Area de Gerenciamento de usuarios (lista)
cria_user_list(){
    list=
    
    for i in $(cat /etc/passwd | grep xensh | sed 's/,/:/g' | cut -d":" -f1,8 | sort)
      do
      value=($(echo $i | sed 's/:/ /'))
      list="$list ${value[1]} ${value[0]}"
    done

}
nao_existe_usuarios(){
	DIALOG \
	--cancel-label "Menu" \
	--yesno "Nao existe usuarios cadastrados.\n
	Deseja cadastrar um novo usuario agora?" 0 0
#	echo $?
#	exit
	case $? in 
	    0) create_xen
	    ;;
	    1) menu
	    ;;
	esac
}
gerenciamento() {
    cria_user_list
# Exibindo menu com a lista
    if [ ! $list ];
    	then
    	nao_existe_usuarios
    else
        VER_VM=$(DIALOG \
	--cancel-label "Menu" \
	--menu "Selecione um usuario para visualizacao:" 0 0 0 \
	$list)
    
        case $? in
            0) visualiza
	      ;;
            1) menu
	      ;;
            255) exit 0
	      ;;
        esac
    fi
}

# Area de visualizacao/alteracao de usuario expecifico
visualiza(){
    NOME=$(cat /etc/passwd | grep ",$VER_VM," | sed 's/,/:/g' | cut -d: -f 5)
    
    DATA_USR=($(cat /etc/passwd | grep ",$VER_VM," | sed 's/,/:/g;s/|/:/g'| cut -d: -f 1,6-8,11-16 | sed 's/:/ /g'))
    USR=${DATA_USR[0]}
    TURMA=${DATA_USR[1]}
    MAIL=${DATA_USR[2]}
    VM_FILE=${DATA_USR[3]}
    DT_INI=${DATA_USR[4]}
    DT_TER=${DATA_USR[5]}
    DT_ACE=${DATA_USR[6]}
    HR_INI=${DATA_USR[7]}
    HR_TER=${DATA_USR[8]}
    VM_STAT=$( [ ${DATA_USR[9]} -eq 0 ] && echo Ativa || echo Desativa)
    VM_LINE=$(xm list $VER_VM 2>/dev/null | grep $VER_VM | wc -l)

    OPT_ALT=$(DIALOG --cancel-label "Menu" \
	--help-button \
	--help-label "Lista" \
	--menu "Informacoes do usuario $USR VM $VER_VM:" 0 0 0 \
	1 "Nome: $NOME" \
	2 "Turma: $TURMA" \
	3 "VM: $VER_VM" \
	4 "Data de Inicio: $DT_INI" \
	5 "Data de Termino: $DT_TER" \
	6 "Dias de acesso: $DT_ACE" \
	7 "Hora inicio: $HR_INI:00 Hs" \
	8  "Hora termino: $HR_TER:00 Hs" \
	9 "Status VM: $VM_STAT" \
	10 "Maquina Virtual: $( [ $VM_LINE -eq 1 ] && echo On-line || echo Off-line)")

    case $? in
        1) menu 
	    ;;
	2) gerenciamento
	    ;;
    esac

    cancela()
    {
	case $? in
	    1)
            visualiza
	    ;;
       esac
    }
    case $OPT_ALT in
        1)
	    NOME=$(DIALOG \
		--inputbox "Entre com o novo nome para o usuario:" 0 0 \
		"$NOME")
	    cancela
	    
	    chfn $USR -f "$NOME"
	    visualiza
	    ;;
        2)
	    TURMA=$(DIALOG \
		--inputbox "Entre com a nova turma para o usuario:" 0 0 \
		"$TURMA")
	    cancela	    
	    chfn $USR -r "$TURMA"
	    visualiza
	    ;;
        3)
	    DIALOG \
		--msgbox "A Maquina Virtual nao eh editavel." 0 0
	    visualiza
	    ;;
        4)
	    DIA=$(echo $DT_INI|cut -d "-" -f 1)
	    MES=$(echo $DT_INI|cut -d "-" -f 2)
	    ANO="20$(echo $DT_INI|cut -d "-" -f 3)"
	    DT_INI=$(DIALOG \
		--calendar "Entre com a nova data inicio:" 0 0 \
		$DIA $MES $ANO)
    	    cancela	    
	    DT_INI=$(echo $DT_INI | sed 's|/|-|g' | cut -c 1-6,8,10)
	    
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    visualiza
	    ;;
        5)
	    DIA=$(echo $DT_TER|cut -d "-" -f 1)
	    MES=$(echo $DT_TER|cut -d "-" -f 2)
	    ANO="20$(echo $DT_TER|cut -d "-" -f 3)"
	    
	    DT_TER=$(DIALOG \
		--calendar "Entre com a nova data de termino:" 0 0 \
		$DIA $MES $ANO)
	    cancela
	    DT_TER=$(echo $DT_TER | sed 's|/|-|g' | cut -c 1-6,8,10)
	    
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    visualiza
	    ;;
        6)
	    DT_ACE=$(DIALOG \
		--checklist "Selecione os dias da semana para acesso:" 0 0 0 \
		1 Segunda $([ $(echo $DT_ACE | grep 1) ] && echo on || echo off) \
		2 Terca $([ $(echo $DT_ACE | grep 2) ] && echo on || echo off) \
		3 Quarta $([ $(echo $DT_ACE | grep 3) ] && echo on || echo off) \
		4 Quinta $([ $(echo $DT_ACE | grep 4) ] && echo on || echo off) \
		5 Sexta $([ $(echo $DT_ACE | grep 5) ] && echo on || echo off) \
		6 Sabado $([ $(echo $DT_ACE | grep 6) ] && echo on || echo off) \
		7 Domingo $([ $(echo $DT_ACE | grep 7) ] && echo on || echo off) )
	    
	    cancela
	    DT_ACE=$(echo $DT_ACE | sed 's/"//g' | sed 's/ /-/g')
	    
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    visualiza
	    ;;
        7)
	    HR_INI=$(DIALOG \
		--timebox "Altere o horario inicial (somente campo hora)" 0 50 \
		$HR_INI 0 0)
	    cancela
	    HR_INI=$(echo $HR_INI| cut -d: -f1)
	    
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    sleep 3
	    visualiza
	    ;;
        8)
	    HR_TER=$(DIALOG \
		--timebox "Altere o horario final (somente campo hora)" 0 50 \
		$HR_TER 0 0)
	    cancela
	    HR_TER=$(echo $HR_TER| cut -d: -f1)
	    
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    visualiza
	    ;;
        9)
	    DATA_USR[9]=$(DIALOG \
		--radiolist "Selecione o status da Virtual Machine do usuario:" 0 0 0 \
		0 Ativa $([ ${DATA_USR[9]} -eq 0 ] && echo on || echo off) \
		1 Desativa $([ ${DATA_USR[9]} -eq 1 ] && echo on || echo off) )
	    cancela
	    chfn $USR -o "||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|${DATA_USR[9]}"
	    visualiza
	    ;;
	10)
	    if [ $VM_LINE -eq 1 ]
		then
		# VM On-line (rotina para colocala em mode off-line
		DIALOG \
		    --yesno "Deseja colocar a VM $VER_VM em modo Off-line?" 0 0
		case $? in
		    0)
			xm shutdown $VER_VM
			visualiza
			;;
		    1)
			visualiza
			;;
		esac
	    else
		# VM Off-line (informa q nao eh possivel colaca-la em outro modo)
		DIALOG \
		    --msgbox "A VM ja esta em modo Off-line." 0 0
		visualiza
	    fi
	    ;;
    esac
}

# Funcao de criacao de usuario e VM:

create_xen(){
    FREE_PE=$(VGDISPLAY | awk '/Free  PE/ {print $7 " " $8}')
    DISP_VM=$[ ( $(echo $FREE_PE | cut -d " " -f 1 | sed 's/\.//')0 / 512 ) ]
    if [ $DISP_VM -eq 0 ];
	then
	DIALOG \
	    --msgbox "Nao existe espaco disponivel para criacao de \nnovas Maquinas Virtuais." 0 0
	menu
    else
	USR=1
	create_username(){
	    USR=$(DIALOG \
		--inputbox "Digite o username para o novo usuario:" 0 0 )
	    case $? in
		1) menu
	        ;;
	    esac
        }

        create_vm(){
	    echo "XXX"
	    echo 5
	    echo "Criando senha."
	    echo "XXX"
	    PASS=$(dd if=/dev/random ibs=6 count=1 2>/dev/null | mimencode)
	    if [ $? -eq 0 ]
            then
	    echo "XXX"
	    echo 10
	    echo "Criptografando senha."
	    echo "XXX"
	    CRYPT_PASS=$(mkpasswd $PASS)
	    if [ $? -eq 0 ]
            then 
	    echo "XXX"
	    echo 15
	    echo "Criando conta do usuario."
	    echo "XXX"
	    vm=$(for ((i=1;i<1024;i++))
		do 
# FIX ME 
		if [ ! $(ls /dev/xen/disk$i 2> /dev/null) ]
		    then
		    echo $i | sed 's/ //g'
		    break
		fi
	    done)
	
	    useradd -c "$NOME,$TURMA,@,xen$vm,||$DT_INI|$DT_TER|$DT_ACE|$HR_INI|$HR_TER|0" -m -g xen -p $CRYPT_PASS -s /bin/xensh $USR
 	    if [ $? -eq 0 ]
            then	
	    echo "XXX"
	    echo 20
	    echo "Escrevendo log"
	    echo "XXX"
	    echo -e "$(date +%d/%m/%y) -- $TURMA\t$NOME\t$USR\t$MAIL\txen$vm\t$PASS" >> /var/log/xenprog.log
	    if [ $? -eq 0 ]
            then 
	    echo "XXX"
	    echo 25
	    echo "Criando VBD LVM."
	    echo "XXX"
	    LVCREATE -L512M -n disk$vm xen 2> /dev/null > /dev/null
	    if [ $? -eq 0 ]
            then
	    echo "XXX"
	    echo 30
	    echo "Criando sistema de arquivos em $XEN_VBD/disk$vm."
	    echo "XXX"
	    mkfs.ext3 $XEN_VBD/disk$vm 2> /dev/null > /dev/null
	    if [ $? -eq 0 ]
            then
	    echo "XXX"
	    echo 35
	    echo "Montando VBD LVM."
	    echo "XXX"
	    mount $XEN_VBD/disk$vm /mnt/disk  2> /dev/null > /dev/null
	    if [ $? -eq 0 ]
	    then	
	    echo "XXX"
	    echo 40
	    echo "Montando disco matriz."
	    echo "XXX"
	    mount $XEN_VBD/disk_orig /mnt/image 2> /dev/null > /dev/null
	    if [ $? -eq 0 ]
            then	
	    echo "XXX"
	    echo 45
	    echo "Criando sistema no novo VBD."
	    echo "XXX"
	    cp -a /mnt/image/* /mnt/disk 2> /dev/null > /dev/null
	    if [ $? -eq 0 ] 
	    then	
	    echo "XXX"
	    echo 85
	    echo "Desmontando volumes." 
	    echo "XXX"
	    umount /mnt/image 2> /dev/null > /dev/null
	    umount /mnt/disk 2> /dev/null > /dev/null
	    
	    echo "XXX"
	    echo 90
	    echo "Enviando senha por e-mail para o aluno."
	    echo "XXX"

	    echo -e "
	    Olá $nome

	Voce esta cadastrado no sistema de maquinas virtuais da $INSTITUTION.

	Para acessar sua maquina virtual, voce podera usar o SSH caso esteja no Linux, ou o PUTTY caso ainda use Windows.

	Para que voce tenha acesso seguem as informacoes Importantes: (Nao perca!!!)

	IP do Servidor :  $IP_SERVIDOR
	Porta de Acesso:    $PORTA_SERVIDOR
	Login de Acesso:    $USR
	Senha de Acesso:    $PASS 
	Sua senha de Root:  $NOME_CURSO

	-> Acessando a Maquina Virtual pelo Windows:

	Baixe o programinha putty: http://superdownloads.ubbi.com.br/download/i19845.html

	E preencha as informacoes de IP e Porta para se conectar!

	-> Acessando a Maquina  Virtual pelo Linux:

	Execute o comando:  ssh $USR@$IP_SERVIDOR  -p $PORTA_SERVIDOR -C

	ATENCAO!!! Voce devera trocar sua senha de root logo no primeiro acesso, para sua propria protecao! Para isso execute o comando:

	passwd

	E lembre-se, Eh obrigatario colocar uma SENHA BEM DIFICIL! ;-)

	Dias em que sua maquina estara disponivel: $DT_ACE
	(Sendo 1-Segunda, 2-Terca, 3-Quarta, 4-Quinta, 5-Sexta, 6-Sabado e 7-Domingo)

	Horario que sua Maquina Virtual estara disponivel: Das $HR_INI:00 as $HR_TER:00

	-> Encerrando uma conexao na Maquina Virtual:

	Para SAIR da Maquina Virtual da maneira correta, basta teclar  Ctrl+]

	Isso mesmo a CTRL + ] (Fecha Colchete!) :-)

	Bom Acesso!

	Equipe $INSTITUTION" > /tmp/mail.$USR

	    sudo -u contato mail -s "Senha de acesso para Maquina Virtual XEN $NOME_CURSO" -b $EMAIL_CURSO  $MAIL < /tmp/mail.$USR	
	if [ $? -eq 0 ]
	then
	    rm /tmp/mail.$USR

	    echo "XXX"
	    echo 100
	    echo "Finalizado."
	    echo "XXX"
	else
	DIALOG --msgbox "ERRO ao enviar o email de notificacao de criacao da maquina virtual" 0 0
	fi
	else
	DIALOG --msgbox "ERRO ao copiar os arquivos da maquina virtual" 0 0
	fi
	else
	DIALOG --msgbox "ERRO ao montar o volume logico da maquina exemplo" 0 0
	fi
	else
	DIALOG --msgbox "ERRO ao montar o volume logico da maquina virtual" 0 0
 	fi
	else
	DIALOG --msgbox "ERRO ao formatar o volume logico da maquina virtual" 0 0
	fi
        else 
        DIALOG --msgbox "ERRO ao criar o volume logico da maquina virtual" 0 0
	fi
        else
        DIALOG --msgbox "ERRO ao logar a criacao da maquina virtual." 0 0
	fi
        else
        DIALOG --msgbox "ERRO ao adicionar usuario no sistema" 0 0
	fi
	else
        DIALOG --msgbox "ERRO ao criptografar a senha do usuario" 0 0
	fi
	else 
        DIALOG --msgbox "ERRO ao criar a senha do usuario" 0 0
	fi
	}
    
	while [ "$USR" = "1" ] || [ $(id $USR 2> /dev/null > /dev/null && echo 1 || echo 0) -eq 1 ] || [ $(echo -n $USR | wc -c) -lt 3 ]
	  do
	  create_username
	done
    
	NOME=$(DIALOG \
	    --inputbox "Nome completo:" 0 0 )
	case $? in
	    1) menu
	    ;;
	esac
    
	MAIL=$(DIALOG \
	    --inputbox "E-mail:" 0 0 )
	case $? in
	    1) menu
	    ;;
	esac
    
	TURMA=$(DIALOG \
	    --inputbox "Turma:" 0 0 $TURMA)
	case $? in
	    1) menu
	    ;;
	esac
    
# Insere Data de inicio
    
    
	DT_INI=$(DIALOG \
	    --calendar "Data de inicio:" 0 0 $DT_INI_OLD)
	case $? in
	    1) menu
	    ;;
	esac
    
	DT_INI_OLD=$(echo $DT_INI | sed 's|/| |g')
	DT_INI=$(echo $DT_INI | sed 's|/|-|g' | cut -c 1-6,8,10)
    
    
# Insere Data de termino
    
	DT_TER=$(DIALOG \
	    --calendar "Data de termino:" 0 0 $DT_TER_OLD)
	case $? in
	    1) menu
	    ;;
	esac
    
	DT_TER_OLD=$(echo $DT_TER | sed 's|/| |g')
	DT_TER=$(echo $DT_TER | sed 's|/|-|g' | cut -c 1-6,8,10)
    
    
# Insere dias da semana de acesso
    
	DT_ACE=$(DIALOG \
	    --checklist "Selecione os dias da semana para acesso:" 0 0 0 \
	    1 Segunda $([ $(echo $DT_ACE | grep 1) ] && echo on || echo off) \
	    2 Terca $([ $(echo $DT_ACE | grep 2) ] && echo on || echo off) \
	    3 Quarta $([ $(echo $DT_ACE | grep 3) ] && echo on || echo off)\
	    4 Quinta $([ $(echo $DT_ACE | grep 4) ] && echo on || echo off) \
	    5 Sexta $([ $(echo $DT_ACE | grep 5) ] && echo on || echo off) \
	    6 Sabado $([ $(echo $DT_ACE | grep 6) ] && echo on || echo off) \
	    7 Domingo $([ $(echo $DT_ACE | grep 7) ] && echo on || echo off) )
	case $? in
	    1) menu
	    ;;
	esac
	
	DT_ACE=$(echo $DT_ACE | sed 's/"//g' | sed 's/ /-/g')
	
	
	HR_INI=$(DIALOG \
	    --timebox "Horario inicial (somente campo hora)" 0 50 $([ ! $HR_INI ] && echo 0 || echo $HR_INI) 0 0) 
	case $? in
	    1) menu
	    ;;
	esac
	
	HR_INI=$(echo $HR_INI| cut -d: -f1)
	
	HR_TER=$(DIALOG \
	    --timebox "Horario final (somente campo hora)" 0 50 $([ ! $HR_TER ] && echo 0 || echo $HR_TER) 0 0)
	case $? in
	    1) menu
	    ;;
	esac
	
	HR_TER=$(echo $HR_TER| cut -d: -f1)
	
	
	DIALOG \
	    --backtitle "As informacoes estao corretas?" \
	    --yesno "
      Nome completo:    $NOME
      Turma:            $TURMA
      E-mail:           $MAIL
      Data de inicio:    $DT_INI
      Data de termino:  $DT_TER
      Dias de acesso:   $DT_ACE
      Hora inicial:     $HR_INI
      Hora final:       $HR_TER" 0 0
	case $? in
	    0) 
	    create_vm | DIALOG --gauge "Aguarde..." 20 70 0
	    DIALOG \
		--ok-label OK \
		--msgbox "Usuario $USR e Maquina Virtual adicionados com sucesso." 0 0
	    case $? in
		*) menu
		;;
	    esac
	    ;;
	    1)
	    create_xen
	    ;;
	esac
    fi
}

list_remove(){
    cria_user_list
    
# Exibindo menu com a lista
    if [ ! $list ];
	then
	DIALOG \
	--cancel-label "Menu" \
	--msgbox "Nao existe nenhuma Maquina Virtual cadastrada." 0 0
	menu
    else
	VER_VM=$(DIALOG \
	    --cancel-label "Menu" \
	    --menu "Selecione um usuario/VM para remocao:" 0 0 0 \
	    $list)
    
    	case $? in
            0) remove
	      ;;
            1) menu
	      ;;
            255) exit 0
	      ;;
    	esac
    fi
}

remove(){
    USR=$(cat /etc/passwd | grep ",$VER_VM," | cut -d: -f1)
    DIALOG \
	--yesno "Voce selecionou para a para remocao:

Usuario: $USR
Maquina Virtual: $VER_VM

Confirma a remocao?
" 0 0
    case $? in
        0) 
#	rm -rf $XEN_CONF/$VER_VM
	    LVREMOVE -f $XEN_VBD/disk$(echo $VER_VM | cut -d n -f 2)
	    if [ $? -eq 0 ]
	    then
	    deluser $USR
	    if [ $? -eq 0 ]
	    then
	    DIALOG \
		--ok-label OK \
		--msgbox "Usuario e Virtual Machine removidos com sucesso." 0 0
	    else
	    DIALOG --msgbox "Erro no comando deluser para remover o usuario" 0 0
	    fi
	    else
	    DIALOG --msgbox "Nao foi possivel remover o volume logico do usuario" 0 0 
	    fi

	    menu
	    ;;
        1) menu
	    ;;
        255) exit 0
	    ;;
    esac
}

list_concerta(){
    cria_user_list
    
    if [ ! $list ];
    	then
	DIALOG \
	--cancel-label "Menu" \
	--yesno "Nao existem Maquinas Virtuais cadastradas.\n
	Deseja cadastrar uma nova maquina virtual agora?" 0 0
#	echo $?
#	exit
	case $? in 
	    0) create_xen
	    ;;
	    1) menu
	    ;;
	esac
    else
# Exibindo menu com a lista
    VER_VM=$(DIALOG \
	--cancel-label "Menu" \
	--menu "Selecione um usuario/VM para conserto:" 0 0 0 \
	$list)
    case $? in
        0) concerta
	    ;;
        1) menu
	    ;;
        255) exit 0
	    ;;
    esac
    fi
}

concerta(){
    vm=$(echo $VER_VM | cut -d n -f2)
    echo "Reformatando VBD."
    mkfs.ext3 $XEN_VBD/disk$vm #2> /dev/null > /dev/null
    if [ $? -eq 0 ]
    then
    echo "Montando VBD."
    mount $XEN_VBD/disk$vm /mnt/disk  #2> /dev/null > /dev/null
    if [ $? -eq 0 ]
    then
    echo "Montando disco matriz."
    mount $XEN_VBD/disk_orig /mnt/image #2> /dev/null > /dev/null
    if [ $? -eq 0 ]
    then 
    echo "Criando sistema no VBD."
    cp -a /mnt/image/* /mnt/disk #2> /dev/null > /dev/null
    if [ $? -eq 0 ]
    then 
    echo "Desmontando volumes." 
    umount /mnt/image #2> /dev/null > /dev/null
    if [ $? -eq 0 ]
    then
    umount /mnt/disk #2> /dev/null > /dev/null
    if [ $? -eq 0 ] 
    then
    sleep 10 
    DIALOG \
	--ok-label Menu \
	--beep \
	--msgbox "Operacao realizada com sucesso." 0 0
	
   else
#debug   sleep 5
   DIALOG --msgbox "ERRO para desmontar o disco da nova maquina virtual" 0 0
   fi
   else 
#debug   sleep 5
   DIALOG --msgbox "ERRO para desmontar o disco matriz" 0 0
   fi
   else 
#debug   sleep 5
   DIALOG --msgbox "ERRO durante a copia de arquivos " 0 0 
   fi
   else
#debug   sleep 5
   DIALOG --msgbox "ERRO durante a montagem do disco matriz" 0 0
   fi
   else 
#debug   sleep 5 
   DIALOG --msgbox "ERRO durante a montagem do VBD" 0 0
   fi
   else
#debug   sleep 5
   DIALOG --msgbox "ERRO durante a formatacao do VBD" 0 0
   fi
    menu   
}

status_menu(){
    
    OPT=$(DIALOG \
	--ok-label "Selecionar" \
	--cancel-label "Menu" \
	--menu "Escolha uma opcao:" 0 0 0 \
	1 "Recursos do sistema de VBDs e VMs" \
	2 "Maquinas Virtuais ativas." \
	3 "Sistema de log de acesso por usuario" )
    case $? in
        1)
	    menu
	    ;;
    esac

    case $OPT in
	1) # "Recursos do sistema de VBDs (Virtual Block Devices)"
	    MAX_LV=$(VGDISPLAY | awk '/MAX LV/ {print $3}')
	    CUR_LV=$(VGDISPLAY | awk '/Cur LV/ {print $3}')
	    TAM_VG=$(VGDISPLAY | awk '/VG Size/ {print $3 " " $4}')
	    ALLOC_PE=$(VGDISPLAY | awk '/Alloc PE/ {print $7 " " $8}')
	    FREE_PE=$(VGDISPLAY | awk '/Free  PE/ {print $7 " " $8}')

	    CAPVM_T=$[ ( $(echo $TAM_VG | cut -d " " -f 1 | sed 's/\.//')0 / 512 - 1 ) ]
	    CAPVM_A=$[ ( $(echo $ALLOC_PE | cut -d " " -f 1 | sed 's/\.//')0 / 512 - 1 ) ]
	    DISP_VM=$[ ( $(echo $FREE_PE | cut -d " " -f 1 | sed 's/\.//')0 / 512 ) ]

	    MSG=$( echo "
Informacoes sobre Recursos de Virutal Block Devices em LVM
----------------------------------------------------------
    Capacidade maxima de Volumes Logicos.................: $MAX_LV    Volumes Logicos alocados no sistema..................: $CUR_LV
    Tamanho total do Grupo de Volume.....................: $TAM_VG
    Espaco alocado no Grupo de Volume....................: $ALLOC_PE
    Espaco disponivel no Grupo de Volume.................: $FREE_PE

Informacoes sobre Recursos de Maquinas Virutais
----------------------------------------------------------
    Capacidade maxima de Maquinas Virtuais...............: $CAPVM_T
    Capacidade em uso por Maquinas Virutais..............: $CAPVM_A
    Capacidade disponivel para novas Maquinas Virtuais...: $DISP_VM

" | sed 's/Size//')

	    DIALOG \
		--ok-label "Voltar" \
		--backtitle "Informacoes sobre VBDs e VMs" \
		--msgbox "$MSG" 0 0
	    status_menu
	    ;;
	2) # "Maquinas Virtuais ativas."
	    num=
	    for vm_on in $(xm list | awk '/xen/ {print $1}')
	      do
	      let num++
	      user_vm=$(cat /etc/passwd | grep ",$vm_on," | cut -d: -f1)
	      vm_list="$vm_list $vm_on $user_vm"
	    done
	    
	    if [ $num ]
		then
		VER_VM=$(DIALOG \
		    --ok-label "Ver info" \
		    --cancel-label "Voltar" \
		    --menu "Para visualizar :" 0 0 0 \
		    $vm_list)
		case $? in
		    0) 
			vm_list=
			visualiza
			;;
		    1) 
			vm_list=
			status_menu
			;;
		esac   
	    else
		DIALOG \
		    --ok-label "Voltar" \
		    --backtitle "Informacoes sobre VBDs" \
		    --msgbox "$MSG" 0 0		
		status_menu
	    fi
	    num=
	    ;;
	3) # "Sistema de log de acesso por usuario"
	sistlog(){
	    cria_user_list
	    if [ ! $list ] 
	       then
	       nao_existe_usuarios
	    else
	
	    VER_LOG=$(DIALOG \
		--cancel-label "Menu" \
		--menu "Selecione um usuario para visualizacao do log:" 0 0 0 \
		$list)
	    case $? in
		0) 
		    last $VER_LOG | cut -c 40- > /tmp/$VER_LOG.log
		    DIALOG \
			--backtitle "Log do usuario $VER_LOG" \
			--textbox /tmp/$VER_LOG.log 20 60
		    sistlog
		    ;;
		1) 
		    menu
		    ;;
	    esac
	    fi
         }
	 sistlog
	 ;;

     esac
     }

menu
